# AUTO-GENERATED by tools/generate_lookups.py - do not edit by hand.
# Regenerate with: python tools/generate_lookups.py --file <rom> --vanilla

from structures.chest import AddressChest
from tables import AncientChest1Object


class AncientChests1:
    """Named access to vanilla ancient-cave chests, table 1 (named by item)."""
    AWAKE = AddressChest.from_table(AncientChest1Object.address, 0)
    SHRIEK = AddressChest.from_table(AncientChest1Object.address, 1)
    MYSTERY_PIN = AddressChest.from_table(AncientChest1Object.address, 2)
    MAGIC_GUARD = AddressChest.from_table(AncientChest1Object.address, 3)
    POWER_GOURD = AddressChest.from_table(AncientChest1Object.address, 4)
    MIND_GOURD = AddressChest.from_table(AncientChest1Object.address, 5)
    LIFE_POTION = AddressChest.from_table(AncientChest1Object.address, 6)
    SPELL_POTION = AddressChest.from_table(AncientChest1Object.address, 7)
    SPEED_POTION = AddressChest.from_table(AncientChest1Object.address, 8)
    MIND_POTION = AddressChest.from_table(AncientChest1Object.address, 9)
    POWER_POTION = AddressChest.from_table(AncientChest1Object.address, 10)
    BRAVE = AddressChest.from_table(AncientChest1Object.address, 11)
    BOOMERANG = AddressChest.from_table(AncientChest1Object.address, 12)
    BIG_BOOMER = AddressChest.from_table(AncientChest1Object.address, 13)
    EX_BOOMER = AddressChest.from_table(AncientChest1Object.address, 14)
    CONFUSE_BALL = AddressChest.from_table(AncientChest1Object.address, 15)
    ICE_BALL = AddressChest.from_table(AncientChest1Object.address, 16)
    FIRE_BALL = AddressChest.from_table(AncientChest1Object.address, 17)
    SLEEP_BALL = AddressChest.from_table(AncientChest1Object.address, 18)
    TERROR_BALL = AddressChest.from_table(AncientChest1Object.address, 19)
    SMOKE_BALL = AddressChest.from_table(AncientChest1Object.address, 20)
    FREEZE_BALL = AddressChest.from_table(AncientChest1Object.address, 21)
    ANTIDOTE = AddressChest.from_table(AncientChest1Object.address, 22)
    MAGIC_FRUIT = AddressChest.from_table(AncientChest1Object.address, 23)
    EX_MAGIC = AddressChest.from_table(AncientChest1Object.address, 24)
    HI_MAGIC = AddressChest.from_table(AncientChest1Object.address, 25)
    EX_MAGIC_26 = AddressChest.from_table(AncientChest1Object.address, 26)
    HI_MAGIC_27 = AddressChest.from_table(AncientChest1Object.address, 27)
    MIRACLE = AddressChest.from_table(AncientChest1Object.address, 28)
    REGAIN = AddressChest.from_table(AncientChest1Object.address, 29)
    CURSELIFTER = AddressChest.from_table(AncientChest1Object.address, 30)
