# AUTO-GENERATED by tools/generate_lookups.py - do not edit by hand.
# Regenerate with: python tools/generate_lookups.py --file <rom> --vanilla

from structures.chest import AddressChest
from tables import AncientChest2Object


class AncientChests2:
    """Named access to vanilla ancient-cave chests, table 2 (named by item)."""
    POTION = AddressChest.from_table(AncientChest2Object.address, 0)
    HI_MAGIC = AddressChest.from_table(AncientChest2Object.address, 1)
    MIRACLE = AddressChest.from_table(AncientChest2Object.address, 2)
    HI_POTION = AddressChest.from_table(AncientChest2Object.address, 3)
    POTION_4 = AddressChest.from_table(AncientChest2Object.address, 4)
    EX_POTION = AddressChest.from_table(AncientChest2Object.address, 5)
    REGAIN = AddressChest.from_table(AncientChest2Object.address, 6)
    EX_MAGIC = AddressChest.from_table(AncientChest2Object.address, 7)
    HI_MAGIC_8 = AddressChest.from_table(AncientChest2Object.address, 8)
