# AUTO-GENERATED by tools/generate_lookups.py - do not edit by hand.
# Regenerate with: python tools/generate_lookups.py --file <rom> --vanilla

from structures.formation import BattleFormation
from tables import BossFormationObject
from helpers.bits import find_table_pointer


class BossFormations:
    """Named access to vanilla boss battle formations (index-named)."""
    BOSS_FORMATION_0 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 0))
    BOSS_FORMATION_1 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 1))
    BOSS_FORMATION_2 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 2))
    BOSS_FORMATION_3 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 3))
    BOSS_FORMATION_4 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 4))
    BOSS_FORMATION_5 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 5))
    BOSS_FORMATION_6 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 6))
    BOSS_FORMATION_7 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 7))
    BOSS_FORMATION_8 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 8))
    BOSS_FORMATION_9 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 9))
    BOSS_FORMATION_10 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 10))
    BOSS_FORMATION_11 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 11))
    BOSS_FORMATION_12 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 12))
    BOSS_FORMATION_13 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 13))
    BOSS_FORMATION_14 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 14))
    BOSS_FORMATION_15 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 15))
    BOSS_FORMATION_16 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 16))
    BOSS_FORMATION_17 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 17))
    BOSS_FORMATION_18 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 18))
    BOSS_FORMATION_19 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 19))
    BOSS_FORMATION_20 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 20))
    BOSS_FORMATION_21 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 21))
    BOSS_FORMATION_22 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 22))
    BOSS_FORMATION_23 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 23))
    BOSS_FORMATION_24 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 24))
    BOSS_FORMATION_25 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 25))
    BOSS_FORMATION_26 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 26))
    BOSS_FORMATION_27 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 27))
    BOSS_FORMATION_28 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 28))
    BOSS_FORMATION_29 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 29))
    BOSS_FORMATION_30 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 30))
    BOSS_FORMATION_31 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 31))
    BOSS_FORMATION_32 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 32))
    BOSS_FORMATION_33 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 33))
    BOSS_FORMATION_34 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 34))
    BOSS_FORMATION_35 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 35))
    BOSS_FORMATION_36 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 36))
    BOSS_FORMATION_37 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 37))
    BOSS_FORMATION_38 = BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, 38))
