# AUTO-GENERATED by tools/generate_lookups.py - do not edit by hand.
# Regenerate with: python tools/generate_lookups.py --file <rom> --vanilla

from structures.capsule import CapsuleMonster


class Capsules:
    """Named access to vanilla capsule monsters."""
    FOOMY_S = CapsuleMonster.from_index(0)
    FOOMY_M = CapsuleMonster.from_index(1)
    FOOMY_L = CapsuleMonster.from_index(2)
    FOOMY_H = CapsuleMonster.from_index(3)
    GOLD_FOX = CapsuleMonster.from_index(4)
    SHAGGY = CapsuleMonster.from_index(5)
    SPRITE = CapsuleMonster.from_index(6)
    CUPID = CapsuleMonster.from_index(7)
    TWINKLE = CapsuleMonster.from_index(8)
    UNICORN = CapsuleMonster.from_index(9)
    HARD_HAT = CapsuleMonster.from_index(10)
    BLUEBIRD = CapsuleMonster.from_index(11)
    WINGED_HORSE = CapsuleMonster.from_index(12)
    GREEN_TITAN = CapsuleMonster.from_index(13)
    SKY_DRAGON = CapsuleMonster.from_index(14)
    RED_FISH = CapsuleMonster.from_index(15)
    TOADIE = CapsuleMonster.from_index(16)
    SEA_GIANT = CapsuleMonster.from_index(17)
    BLUE_TITAN = CapsuleMonster.from_index(18)
    FISH_HEAD = CapsuleMonster.from_index(19)
    MYCONIDO = CapsuleMonster.from_index(20)
    WOLFMAN = CapsuleMonster.from_index(21)
    MINI_IMP = CapsuleMonster.from_index(22)
    BIG_IMP = CapsuleMonster.from_index(23)
    RED_DRAGON = CapsuleMonster.from_index(24)
    RADDISHER = CapsuleMonster.from_index(25)
    RED_CAP = CapsuleMonster.from_index(26)
    GIANT = CapsuleMonster.from_index(27)
    STONEHEAD = CapsuleMonster.from_index(28)
    CENTAUR = CapsuleMonster.from_index(29)
    ARMOR_DOG = CapsuleMonster.from_index(30)
    WINGED_LION = CapsuleMonster.from_index(31)
    WING_LIZARD = CapsuleMonster.from_index(32)
    BLAZE_DRAGON = CapsuleMonster.from_index(33)
    FIREBIRD = CapsuleMonster.from_index(34)
