# AUTO-GENERATED by tools/generate_lookups.py - do not edit by hand.
# Regenerate with: python tools/generate_lookups.py --file <rom> --vanilla

from structures.maiden import Clare, Lisa, Marie


class Maidens:
    """Named access to the maidens."""
    LISA = Lisa
    MARIE = Marie
    CLARE = Clare
