# AUTO-GENERATED by tools/generate_lookups.py - do not edit by hand.
# Regenerate with: python tools/generate_lookups.py --file <rom> --vanilla

from structures.character import PlayableCharacter


class Players:
    """Named access to the playable characters."""
    MAXIM = PlayableCharacter.from_index(0)
    SELAN = PlayableCharacter.from_index(1)
    GUY = PlayableCharacter.from_index(2)
    ARTY = PlayableCharacter.from_index(3)
    TIA = PlayableCharacter.from_index(4)
    DEKAR = PlayableCharacter.from_index(5)
    LEXIS = PlayableCharacter.from_index(6)
