"""
Always load the patches from the bottom up,
so that the most difficult patch is loaded last.
IE: Vanilla > Frue > Spekkio or Kureji

This ensures the correct table objects are known.
Not all patches include all objects, some only include the one's that differ.
(Kureji only includes the objects that are different from Frue)
"""

# TODO: Currently there's no real support for anything besides vanilla.

from args import args
from enums.patches import Patch

from .zones import ZoneObject


if args.selected_patch.value >= Patch.VANILLA.value:
    from .vanilla import (
        AncientChest1Object,
        AncientChest2Object,
        BlueChestObject,
        BossFormationObject,
        CapAttackObject,
        CapPaletteObject,
        CapSpritePTRObject,
        CapsuleLevelObject,
        CapsuleObject,
        CharacterObject,
        CharExpObject,
        CharGrowthObject,
        CharLevelObject,
        ChestObject,
        EventInstObject,
        FormationObject,
        InitialEquipObject,
        IPAttackObject,
        ItemNameObject,
        ItemObject,
        MapEventObject,
        MapFormationsObject,
        MapMetaObject,
        MonsterMoveObject,
        MonsterObject,
        OverPaletteObject,
        OverSpriteObject,
        RoamingNPCObject,
        ShopObject,
        SpellObject,
        SpriteMetaObject,
        TownSpriteObject,
        WordObject,
    )  # type: ignore[UnusedImport]

if args.selected_patch.value >= Patch.FRUE.value:
    from .frue import (
        AncientChest1Object,
        AncientChest2Object,
        BlueChestObject,
        BossFormationObject,
        CapAttackObject,
        CapPaletteObject,
        CapSpritePTRObject,
        CapsuleLevelObject,
        CapsuleObject,
        CharacterObject,
        CharExpObject,
        CharGrowthObject,
        CharLevelObject,
        ChestObject,
        EventInstObject,
        FormationObject,
        InitialEquipObject,
        IPAttackObject,
        ItemNameObject,
        ItemObject,
        MapEventObject,
        MapFormationsObject,
        MapMetaObject,
        MonsterMoveObject,
        MonsterObject,
        OverPaletteObject,
        OverSpriteObject,
        RoamingNPCObject,
        ShopObject,
        SpellObject,
        SpriteMetaObject,
        TownSpriteObject,
        WordObject,
    )  # type: ignore[UnusedImport]

if args.selected_patch.value is Patch.SPEKKIO:
    from .spekkio import (
        AncientChest1Object,
        AncientChest2Object,
        BlueChestObject,
        BossFormationObject,
        CapAttackObject,
        CapPaletteObject,
        CapSpritePTRObject,
        CapsuleLevelObject,
        CapsuleObject,
        CharacterObject,
        CharExpObject,
        CharGrowthObject,
        CharLevelObject,
        ChestObject,
        EventInstObject,
        FormationObject,
        InitialEquipObject,
        IPAttackObject,
        ItemNameObject,
        ItemObject,
        MapEventObject,
        MapFormationsObject,
        MapMetaObject,
        MonsterMoveObject,
        MonsterObject,
        OverPaletteObject,
        OverSpriteObject,
        RoamingNPCObject,
        ShopObject,
        SpellObject,
        SpriteMetaObject,
        TownSpriteObject,
        WordObject,
    )  # type: ignore[UnusedImport]

if args.selected_patch is Patch.KUREJI:
    from .kureji import (
        AncientChest1Object,
        AncientChest2Object,
        BlueChestObject,
        CapPaletteObject,
        CapSpritePTRObject,
        CapsuleObject,
        CharacterObject,
        CharGrowthObject,
        ChestObject,
        ItemNameObject,
        ItemObject,
        MonsterMoveObject,
        MonsterObject,
        ShopObject,
        SpellObject,
    )  # type: ignore[UnusedImport]

__all__ = [
    "AncientChest1Object",
    "AncientChest2Object",
    "BlueChestObject",
    "BossFormationObject",
    "CapAttackObject",
    "CapPaletteObject",
    "CapSpritePTRObject",
    "CapsuleLevelObject",
    "CapsuleObject",
    "CharExpObject",
    "CharGrowthObject",
    "CharLevelObject",
    "CharacterObject",
    "ChestObject",
    "EventInstObject",
    "FormationObject",
    "IPAttackObject",
    "InitialEquipObject",
    "ItemNameObject",
    "ItemObject",
    "MapEventObject",
    "MapFormationsObject",
    "MapMetaObject",
    "MonsterMoveObject",
    "MonsterObject",
    "OverPaletteObject",
    "OverSpriteObject",
    "RoamingNPCObject",
    "ShopObject",
    "SpellObject",
    "SpriteMetaObject",
    "TownSpriteObject",
    "WordObject",
    "ZoneObject",
]
