"""Opcode metadata for the Lufia II event-script bytecode.

Two independent facts are kept here:

- :data:`OPERAND_SHAPES` -- the authoritative *operand shape* of every opcode, which drives the
  byte parser (transcribed from terrorwave's verified ``event_instructions.txt``). A shape is a
  tuple whose elements are either an ``int`` (a fixed operand of that many little-endian bytes) or
  one of the string tokens :data:`TEXT`, :data:`ADDR`, :data:`POINTERS`, :data:`VARIABLE`.
- :data:`OP_CODES` -- the human ``{params, comment}`` description table (moved verbatim from the
  retired ``structures/events.py``), used only for enriching dump comments.

Where the two disagree (notably ``0x01``-``0x06``, reinterpreted inside text mode) the operand
shape is authoritative for the byte parser; the descriptive table applies only to comments.
"""

from string import ascii_letters, digits, punctuation
from typing import TypedDict


TEXT = "text"
ADDR = "addr"
POINTERS = "pointers"
VARIABLE = "variable"

type ShapeToken = int | str
type Shape = tuple[ShapeToken, ...]


class OpCode(TypedDict):
    """Human-readable description of an opcode (kept from the original ``events.py``)."""

    params: int
    comment: str


# Flow-control / text-mode opcode groups (moved verbatim from ``events.py``).
FLOW_CONTROL = [0x12, 0x1C, 0x14, 0x15, 0x6A]
ENTER_TEXT_MODE = [0x08, 0x13, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x67, 0x6D, 0x6E, 0x9E]
EXIT_TEXT_MODE = [0x00, 0x01, 0x0B]

SPACE = " "
VALID_ASCII_CHARACTERS = ascii_letters + digits + punctuation + SPACE


# Authoritative operand shapes (from terrorwave ``event_instructions.txt``); see 07_game_reference.md.
# An empty tuple means "no operands".
OPERAND_SHAPES: dict[int, Shape] = {
    0x00: (),
    0x01: (2,),
    0x02: (2,),
    0x03: (2,),
    0x04: (2,),
    0x05: (2,),
    0x06: (2,),
    0x07: (1,),
    0x08: (TEXT,),
    0x0C: (),
    0x0D: (),
    0x10: (POINTERS,),
    0x11: (),
    0x12: (1, POINTERS),
    0x13: (TEXT,),
    0x14: (VARIABLE,),
    0x15: (1, ADDR),
    0x16: (1, 1, 1),
    0x17: (1,),
    0x18: (1,),
    0x19: (),
    0x1A: (1,),
    0x1B: (1,),
    0x1C: (ADDR,),
    0x1D: (1, 1),
    0x1E: (1, 1),
    0x20: (1, 1),
    0x21: (1, 1),
    0x22: (2,),
    0x23: (1, 1),
    0x24: (1, 1),
    0x25: (1, 1),
    0x28: (),
    0x29: (1, 1, 1),
    0x2B: (1,),
    0x2C: (1,),
    0x2D: (1,),
    0x2E: (1,),
    0x30: (1, 1),
    0x31: (1, 1),
    0x32: (1, 1),
    0x33: (1, 1),
    0x34: (1, 1),
    0x35: (1, 1, 1),
    0x37: (1,),
    0x38: (1,),
    0x39: (),
    0x3B: (1,),
    0x3C: (),
    0x3D: (1,),
    0x40: (2,),
    0x41: (1, 1),
    0x42: (),
    0x43: (1, 1),
    0x45: (1, 1, 1),
    0x47: (1,),
    0x48: (1, 1),
    0x49: (1,),
    0x4A: (1,),
    0x4B: (1,),
    0x4C: (1,),
    0x4D: (1,),
    0x4F: (1,),
    0x50: (),
    0x51: (),
    0x53: (1,),
    0x54: (1,),
    0x55: (1,),
    0x56: (),
    0x57: (),
    0x58: (1,),
    0x59: (1,),
    0x5A: (1, 1, 1),
    0x5B: (1, 1),
    0x5E: (1,),
    0x60: (1, 1),
    0x61: (TEXT,),
    0x62: (TEXT,),
    0x63: (TEXT,),
    0x64: (TEXT,),
    0x65: (TEXT,),
    0x66: (TEXT,),
    0x67: (TEXT,),
    0x68: (1, 1),
    0x69: (1,),
    0x6A: (1, ADDR),
    0x6B: (),
    0x6C: (1, 1, 1),
    0x6D: (TEXT,),
    0x6E: (TEXT,),
    0x6F: (1,),
    0x70: (),
    0x71: (),
    0x72: (),
    0x73: (1, 1),
    0x74: (1,),
    0x75: (),
    0x76: (),
    0x77: (1,),
    0x78: (),
    0x79: (),
    0x7B: (1, 1),
    0x7C: (1,),
    0x7D: (1,),
    0x7E: (1,),
    0x7F: (1,),
    0x80: (1,),
    0x81: (1,),
    0x82: (),
    0x83: (1,),
    0x85: (1, 1),
    0x86: (1, 1),
    0x87: (1, 1),
    0x88: (),
    0x89: (1,),
    0x8A: (),
    0x8B: (1, 1, 1),
    0x8C: (1, 1, 1),
    0x8D: (1, 1, 1, 1, 1, 1),
    0x8E: (1, 1, 1),
    0x8F: (1, 1, 1),
    0x90: (1, 1, 1),
    0x91: (1, 1),
    0x92: (1,),
    0x94: (1, 1, 1),
    0x95: (1, 1, 1),
    0x97: (),
    0x98: (1, 1),
    0x99: (1,),
    0x9A: (1,),
    0x9C: (1, 1, 1),
    0x9D: (1,),
    0x9E: (TEXT,),
    0x9F: (1, 1, 1),
    0xA0: (1, 1, 1, 1, 1, 1),
    0xA1: (1, 1),
    0xA2: (1,),
    0xA3: (1, 1),
    0xA4: (),
    0xA5: (),
    0xA6: (),
    0xA7: (1,),
    0xA8: (1,),
    0xA9: (1, 1),
    0xAA: (),
    0xAB: (1,),
    0xAD: (1, 1, 1),
    0xAE: (1,),
    0xAF: (1, 1),
    0xB0: (1,),
    0xB1: (1, 1),
    0xB3: (1,),
    0xB4: (1, 1, 1),
    0xB5: (),
    0xB6: (1, 1),
    0xB7: (1,),
    0xB8: (),
    0xB9: (1,),
    0xBA: (1,),
    0xBB: (),
    0xBC: (),
    0xBD: (1, 1),
    0xBE: (1,),
    0xBF: (1, 1, 1),
    0xC0: (1, 1, 1),
    0xC1: (1, 1),
    0xC2: (1, 1, 1, 1, 1, 1),
    0xC3: (1, 1, 1, 1, 1, 1),
    0xC4: (1, 1),
    0xC5: (),
    0xC6: (1, 1),
    0xC7: (),
    0xC9: (1, 1, 1, 1, 1, 1, 1),
    0xCA: (1, 1, 1),
    0xCB: (1,),
    0xCC: (),
}


def operand_shape(opcode: int) -> Shape:
    """Return the operand shape for ``opcode`` or raise ``KeyError`` if it is unknown."""
    return OPERAND_SHAPES[opcode]


# Refer to L2_ScriptEvents.txt for more information. Descriptions only; not used by the parser.
op_codes: dict[int, OpCode] = {
    0x00: {"params": 0, "comment": "=> END"},
    0x01: {"params": 2, "comment": "=> IN TEXT MODE:  End of quote"},
    0x02: {"params": 2, "comment": "=> BRK"},
    0x03: {"params": 2, "comment": "=> IN TEXT MODE:  line break"},
    0x04: {"params": 2, "comment": "XX => IN TEXT MODE:  Pause ([P XX])"},
    0x05: {"params": 2, "comment": "XX => IN TEXT MODE:  05-shift"},
    0x06: {"params": 2, "comment": "XX => IN TEXT MODE:  06-shift"},
    0x07: {"params": 1, "comment": "XX => ???"},
    0x08: {"params": 0, "comment": "=> The character you're talking to speaks."},
    0x09: {"params": 0, "comment": "=> IN TEXT MODE:  Hero's name (Maxim, if you didn't change it)"},
    0x0A: {"params": 2, "comment": "XX YY => 0A-pointer (relative)"},
    0x0B: {"params": 0, "comment": "=> IN TEXT MODE:  Selection Cursor (replaces 0x01 as EOQ byte). See 0x10"},
    0x0C: {"params": 0, "comment": "=> IN TEXT MODE:  ? + line break"},
    0x0D: {"params": 0, "comment": "=> IN TEXT MODE:   + line break"},
    0x0E: {"params": 0, "comment": "=> IN TEXT MODE:  , + line break"},
    0x0F: {"params": 0, "comment": "=> IN TEXT MODE:  . + line break"},
    0x10: {"params": 1, "comment": "XX (P1 P1, ...) => XX Choice, 2-byte pointers to replies."},
    0x11: {"params": 0, "comment": "=> BRK"},
    0x12: {"params": 2, "comment": "XX YY (P1 P1, ...) => ??? YY = the number of pointers"},
    0x13: {"params": 1, "comment": "XX => Character XX speaks spontaneously"},
    0x14: {"params": 1, "comment": "XX ... ? => ??? (0x14 FF => 2-bytes long instruction)"},
    0x15: {"params": 3, "comment": "XX YY ZZ => If the event flag number XX is set  => JUMP TO [script start offset + ZZYY]"},
    0x16: {"params": 3, "comment": "XX YY ZZ => (EXIT) go to map number XX; jump to part YY of the script (?); screen at position ZZ"},
    0x17: {"params": 1, "comment": "XX =>  XX: - 0x00 => rest (at an inn)"},
    0x18: {"params": 1, "comment": "XX => Enter shop menu, XX: shop number"},
    0x19: {"params": 0, "comment": "=> Enter church menu"},
    0x1A: {"params": 1, "comment": "XX => Set event bit number XX"},
    0x1B: {"params": 1, "comment": "XX => Clear event bit number XX"},
    0x1C: {"params": 2, "comment": "XX YY => JUMP TO [script start offset + YYXX]"},
    0x1D: {"params": 2, "comment": "XX YY => Set Variable"},
    0x1E: {"params": 2, "comment": "XX YY => Add Value to Variable"},
    0x20: {"params": 2, "comment": "XX YY => Get YY copies of item number 0x00XX"},
    0x21: {"params": 2, "comment": "XX YY => Get YY copies of item number 0x01XX"},
    0x22: {"params": 2, "comment": "XX YY => Get YYXX GOLD"},
    0x23: {"params": 2, "comment": "XX YY => Party member XX learns the spell YY"},
    0x24: {"params": 2, "comment": "XX YY => Remove item 0XX"},
    0x25: {"params": 2, "comment": "XX YY => Remove item 1XX"},
    0x28: {"params": 0, "comment": "=> ?"},
    0x29: {"params": 3, "comment": "XX YY ZZ => Randomly increases a pot. stat+ of character XX by max ZZ?"},
    0x2B: {"params": 1, "comment": "XX => Character XX joins the party"},
    0x2C: {"params": 1, "comment": "XX => Character XX leaves the party"},
    0x2D: {"params": 1, "comment": "XX => Character XX appears"},
    0x2E: {"params": 1, "comment": "XX => Character XX disappears"},
    0x30: {"params": 2, "comment": "XX YY => Instantly move character XX to pre-defined location YY"},
    0x31: {"params": 2, "comment": "XX YY => Character XX turns (during conversation)"},
    0x32: {"params": 2, "comment": "XX YY => Change NPC wander behavior"},
    0x33: {"params": 2, "comment": "XX YY => Character YY walks route XX"},
    0x34: {"params": 2, "comment": "XX YY => Change the sprite of character XX  (YY = new sprite number)"},
    0x35: {"params": 3, "comment": "XX YY ZZ => Move roaming NPC"},
    0x37: {"params": 1, "comment": "XX => Pause (duration: XX)"},
    0x38: {"params": 1, "comment": "XX => Pause (Longer)"},
    0x39: {"params": 0, "comment": "=> dummy?"},
    0x3B: {"params": 1, "comment": "XX => Show part of the map at pre-defined position XX"},
    0x3C: {"params": 0, "comment": "=> Gather Behind Maxim"},
    0x3D: {"params": 1, "comment": "XX => Hide Behind Maxim"},
    0x40: {"params": 0, "comment": "=> Key check? (Only used in Ancient Cave lobby)"},
    0x41: {"params": 2, "comment": "XX YY => Camera related (follow for X steps?)"},
    0x42: {"params": 0, "comment": "=> same as 0x00"},
    0x43: {"params": 2, "comment": "XX YY => Overwrite Map Tiles"},
    0x45: {"params": 3, "comment": "XX YY ZZ => ?"},
    0x47: {"params": 1, "comment": "XX => Speech border type"},
    0x48: {"params": 2, "comment": "XX YY => ?"},
    0x49: {"params": 1, "comment": "XX => ?"},
    0x4A: {"params": 1, "comment": "XX => ? (appearance of text in text boxes)"},
    0x4B: {"params": 1, "comment": "XX => Select music for battle?"},
    0x4C: {"params": 1, "comment": "XX => Sound? (XX: sound number)"},
    0x4D: {"params": 1, "comment": "XX => ? (sound-related?) (can EXIT)"},
    0x4F: {"params": 1, "comment": "XX => dummy?"},
    0x50: {"params": 0, "comment": "=> ?"},
    0x51: {"params": 0, "comment": "=> ?"},
    0x53: {"params": 1, "comment": "XX => Boss battle with boss party number XX"},
    0x54: {"params": 1, "comment": "XX => Open locked door? (Entrance index?)"},
    0x55: {"params": 1, "comment": "XX => ?"},
    0x56: {"params": 0, "comment": "=> Stop earthquake. See opcode 0x5A."},
    0x57: {"params": 0, "comment": "=> ?"},
    0x58: {"params": 1, "comment": "XX => Fade to black"},
    0x59: {"params": 1, "comment": "XX => Luminosity"},
    0x5A: {"params": 3, "comment": "XX YY ZZ => Make an earthquake"},
    0x5B: {"params": 2, "comment": "XX YY => Play Cutscene"},
    0x5E: {"params": 1, "comment": "XX => ? (EXIT)"},
    0x60: {"params": 2, "comment": "XX YY => ?"},
    0x61: {"params": 0, "comment": "=> Maxim speaks spontaneously (also: Erim in the intro)"},
    0x62: {"params": 0, "comment": "=> Selan speaks"},
    0x63: {"params": 0, "comment": "=> Guy speaks"},
    0x64: {"params": 0, "comment": "=> Artea speaks"},
    0x65: {"params": 0, "comment": "=> Dekar speaks"},
    0x66: {"params": 0, "comment": "=> Tia speaks"},
    0x67: {"params": 0, "comment": "=> Lexis speaks"},
    0x68: {"params": 2, "comment": "XX YY => Character XX use sprite YY (used in map pre-scripts)"},
    0x69: {"params": 1, "comment": "XX => Set Map Properties (escapable, etc.)"},
    0x6A: {"params": 3, "comment": "XX YY ZZ => If the event flag number XX is clear  => JUMP TO [script start offset + ZZYY]"},
    0x6B: {"params": 0, "comment": "=> ?"},
    0x6C: {"params": 3, "comment": "XX YY ZZ => character XX moves; YY: horizontally, ZZ: vertically"},
    0x6D: {"params": 2, "comment": "XX YY => display text like Main programmer"},
    0x6E: {"params": 2, "comment": "XX YY => display text like Akihiro Suzuki"},
    0x6F: {"params": 1, "comment": "XX => Change map music"},
    0x70: {"params": 0, "comment": "=> map music off"},
    0x71: {"params": 0, "comment": "=> ?"},
    0x72: {"params": 0, "comment": "=> ? (sound-related)"},
    0x73: {"params": 2, "comment": "XX YY => display an animation"},
    0x74: {"params": 1, "comment": "XX => Select the background for battles on that map"},
    0x75: {"params": 0, "comment": "=> ?"},
    0x76: {"params": 0, "comment": "=> ?"},
    0x77: {"params": 1, "comment": "XX => same as 0xBE"},
    0x78: {"params": 0, "comment": "=> ?"},
    0x79: {"params": 0, "comment": "=> ?"},
    0x7B: {"params": 2, "comment": "XX YY => Load Monster NPC"},
    0x7C: {"params": 1, "comment": "XX => Set ship upgrades flag"},
    0x7D: {"params": 1, "comment": "XX => Set ship location flag"},
    0x7E: {"params": 1, "comment": "XX => Set ship on map flag"},
    0x7F: {"params": 1, "comment": "XX => Set exit town in ship flag"},
    0x80: {"params": 1, "comment": "XX => Set a ship sprite"},
    0x81: {"params": 1, "comment": "XX => A Capsule Monster joins your party"},
    0x82: {"params": 0, "comment": "=> ?"},
    0x83: {"params": 1, "comment": "XX => Call Exit (EXITS, only used for Chaed)"},
    0x85: {"params": 2, "comment": "XX YY => ?"},
    0x86: {"params": 2, "comment": "XX YY => Character XX moves YY Animation"},
    0x87: {"params": 2, "comment": "XX YY => ?"},
    0x88: {"params": 0, "comment": "=> Set Map Properties"},
    0x89: {"params": 1, "comment": "XX => ?"},
    0x8A: {"params": 0, "comment": "=> ?"},
    0x8B: {"params": 3, "comment": "XX YY ZZ => ?"},
    0x8C: {"params": 3, "comment": "XX YY ZZ =>  ZZ = the sprite that Maxim holds (Gets item)"},
    0x8D: {"params": 6, "comment": "X1..X6 => Wave-warping animation of the Sinistrals at pre-defined position X2"},
    0x8E: {"params": 3, "comment": "XX YY ZZ => ?"},
    0x8F: {"params": 3, "comment": "XX YY ZZ => Wave motion up-down"},
    0x90: {"params": 3, "comment": "XX YY ZZ => Wave motion right-left"},
    0x91: {"params": 2, "comment": "XX YY => ? (affects the last event flag)"},
    0x92: {"params": 1, "comment": "XX => ? (affects the last event flag)"},
    0x94: {"params": 3, "comment": "XX YY ZZ =>"},
    0x95: {"params": 3, "comment": "XX YY ZZ => Screen tint animation"},
    0x97: {"params": 0, "comment": "=> ?"},
    0x98: {"params": 2, "comment": "XX YY => Character XX thunder-warps (at the position YY?)"},
    0x99: {"params": 1, "comment": "XX => ?"},
    0x9A: {"params": 1, "comment": "XX => ?"},
    0x9C: {"params": 3, "comment": "XX YY ZZ => ?"},
    0x9D: {"params": 1, "comment": "XX => ?"},
    0x9E: {"params": 1, "comment": "XX => open a dialog window, XX: top to bottom"},
    0x9F: {"params": 3, "comment": "XX YY ZZ => Wave motion shrink"},
    0xA0: {"params": 6, "comment": "X1..X6 => ?"},
    0xA1: {"params": 2, "comment": "XX YY => ?"},
    0xA2: {"params": 1, "comment": "XX => ? (can EXIT)"},
    0xA3: {"params": 2, "comment": "XX YY => Character XX... moves?"},
    0xA4: {"params": 0, "comment": "=> Pixelation of the screen for a very short time"},
    0xA5: {"params": 0, "comment": "=> load-a-game screen (after losing a boss battle)"},
    0xA6: {"params": 0, "comment": "=> ?"},
    0xA7: {"params": 1, "comment": "XX => ?"},
    0xA8: {"params": 1, "comment": "XX => 0xA8 00: leave items at level 1; 0xA8 01: take back items and stats"},
    0xA9: {"params": 2, "comment": "XX YY => ?"},
    0xAA: {"params": 0, "comment": "=> ?"},
    0xAB: {"params": 1, "comment": "XX => Check if you have enough dragon eggs"},
    0xAD: {"params": 3, "comment": "XX YY ZZ => Dragon eggs related? (Egg Dragon Shrine)"},
    0xAE: {"params": 1, "comment": "XX => ?"},
    0xAF: {"params": 2, "comment": "XX YY => Character XX flickers #YY: related to frequency"},
    0xB0: {"params": 1, "comment": "XX => ?"},
    0xB1: {"params": 2, "comment": "XX YY => ? (affects character number XX)"},
    0xB3: {"params": 1, "comment": "XX => Party Members Change Facing"},
    0xB4: {"params": 3, "comment": "XX YY ZZ => ?"},
    0xB5: {"params": 0, "comment": "=> ?"},
    0xB6: {"params": 2, "comment": "XX YY => ?"},
    0xB7: {"params": 1, "comment": "XX => ?"},
    0xB8: {"params": 0, "comment": "=> ? (can EXIT)"},
    0xB9: {"params": 1, "comment": "XX => Fill IP bar of party member XX"},
    0xBA: {"params": 1, "comment": "XX => ?"},
    0xBB: {"params": 0, "comment": "=> Show the current report"},
    0xBC: {"params": 0, "comment": "=> ? (EXIT)"},
    0xBD: {"params": 2, "comment": "XX YY => ?"},
    0xBE: {"params": 1, "comment": "XX => same as 0x77"},
    0xBF: {"params": 3, "comment": "XX YY ZZ => ?"},
    0xC0: {"params": 3, "comment": "XX YY ZZ => ?"},
    0xC1: {"params": 2, "comment": "XX YY => ?"},
    0xC2: {"params": 6, "comment": "X1..X6 => ?"},
    0xC3: {"params": 6, "comment": "X1..X6 => ?"},
    0xC4: {"params": 2, "comment": "XX YY => Scroll the screen to position x = XX y = YY"},
    0xC5: {"params": 0, "comment": "=> ?"},
    0xC6: {"params": 2, "comment": "XX YY => Displays animation XX on sprite YY?"},
    0xC7: {"params": 0, "comment": "=> ?"},
    0xC9: {"params": 7, "comment": "X1..X7 => ?"},
    0xCA: {"params": 3, "comment": "XX YY ZZ => ?"},
    0xCB: {"params": 1, "comment": "XX => ?"},
    0xCC: {"params": 0, "comment": "=> ?"},
}
