"""Generate the repo-root ``structs.imhex`` ImHex pattern from committed data sources.

This replaces hand-maintaining the ImHex Pattern Language file. It stitches together the three
machine-readable sources already in the repo:

* **Known address data** -- ``src/tables/vanilla.py``: one class per game object holding field
  byte-widths, bitfield name-strings, and either ``address`` + ``count`` (a contiguous table),
  ``address`` + ``count`` + ``grouped`` (a 2-byte *pointer* table -- records live at
  ``base + pointer``), or a ``pointers`` list (scattered records).
* **Lookups** -- ``src/lookups/*.py``: committed auto-generated modules whose members map an
  in-game name to a table index (``POTION = Item.from_index(2)``). These become ImHex ``enum``s so
  fields render as names, not raw numbers.
* **Eventmap dumps** -- ``events_dump.txt``: per-map disassembled event scripts, mined here only for
  each map's name and event-list start address (the scripts themselves are variable-length bytecode
  and are not laid out as structs).

Unlike ``tools/generate_lookups.py`` this script is **ROM-free and takes no CLI arguments**:
``tables/vanilla.py`` imports only ``typing``, the lookups are committed, and ``events_dump.txt`` is
on disk. Run it from anywhere::

    python tools/generate_structs_imhex.py

Output is the repo-root ``structs.imhex`` (overwritten). The file is committed; regenerate it with
this script rather than hand-editing.
"""

import importlib.util
import re
from pathlib import Path
from types import ModuleType

SRC_DIR = Path(__file__).resolve().parent.parent          # .../src
REPO_ROOT = SRC_DIR.parent                                 # repo root
VANILLA_PATH = SRC_DIR / "tables" / "vanilla.py"
LOOKUPS_DIR = SRC_DIR / "lookups"
EVENTS_DUMP = REPO_ROOT / "events_dump.txt"
OUTPUT = REPO_ROOT / "structs.imhex"

HEADER = (
    "// AUTO-GENERATED by src/tools/generate_structs_imhex.py - do not edit by hand.\n"
    "// Regenerate with: python tools/generate_structs_imhex.py\n"
    "//\n"
    "// Open a vanilla Lufia II (USA) ROM in ImHex, then load this pattern. Addresses are raw\n"
    "// (unheadered) ROM file offsets, mirroring src/tables/vanilla.py.\n"
)

# ImHex fixed-width unsigned types by byte size.
INT_TYPE = {1: "u8", 2: "u16", 3: "u24", 4: "u32", 6: "u48", 8: "u64"}

# ImHex Pattern Language reserved words (built-in types + keywords). A data-field or bit name that
# collides with one of these is suffixed with `_` so the pattern still parses.
RESERVED = {
    "u8", "u16", "u24", "u32", "u48", "u64", "u96", "u128",
    "s8", "s16", "s24", "s32", "s48", "s64", "s96", "s128",
    "float", "double", "char", "char16", "bool", "str", "auto", "void",
    "struct", "union", "enum", "bitfield", "using", "fn", "namespace", "return",
    "if", "else", "while", "for", "match", "try", "catch", "in", "out", "ref",
    "be", "le", "signed", "unsigned", "parent", "this", "null", "padding",
    "break", "continue", "import", "as",
}


def safe(name: str) -> str:
    """Suffix a name that collides with an ImHex reserved word (e.g. the field ``str``)."""
    return f"{name}_" if name in RESERVED else name

# Table metadata keys that are not data fields.
META_KEYS = {"address", "count", "pointers", "grouped"}

# --- Field-kind overrides (the `# String` / `# List` intent in vanilla.py is a source comment and
# is lost to introspection, so it is restated here). ---------------------------------------------

# Field names that are fixed-width ASCII strings rather than a single integer.
STRING_FIELDS = {"name_text"}

# (class, field) -> element enum (or None) for byte-arrays that are really lists of indices.
LIST_FIELDS: dict[tuple[str, str], str | None] = {
    ("FormationObject", "monster_indexes"): "MonsterId",
    ("CapsuleObject", "start_skills"): None,
    ("CapsuleObject", "upgrade_skills"): None,
}

# (class, field) -> enum for single integer fields that index another table.
ENUM_FIELDS: dict[tuple[str, str], str] = {
    ("BlueChestObject", "item_index"): "Item",
    ("AncientChest1Object", "item_index"): "Item",
    ("AncientChest2Object", "item_index"): "Item",
}

# Lookup module -> (ImHex enum name, base type). The enum name deliberately differs from the struct
# type names (e.g. `Item` enum vs `ItemObject` struct) so the two never collide.
LOOKUP_ENUMS = [
    ("items.py", "Item", "u16"),
    ("monsters.py", "MonsterId", "u8"),
    ("spells.py", "Spell", "u8"),
    ("zones.py", "Zone", "u8"),
    ("map_events.py", "MapEvents", "u8"),
    ("capsules.py", "Capsule", "u8"),
    ("ip_attacks.py", "IPAttack", "u8"),
    ("words.py", "Word", "u16"),
    ("players.py", "Player", "u8"),
]

_MEMBER_RE = re.compile(r"^\s*([A-Z][A-Z0-9_]*)\s*=\s*\w+\.from_")
_MAP_RE = re.compile(r"^#\s*MAP\s+([0-9A-Fa-f]+)-([0-9A-Fa-f]+)\s*\((.*)\)\s*$")
# Capture the event signature and its script-region start. The `-X-XX` script is the shared
# NPC-load routine (always based at $38000); the map-specific event list is the first other one.
_EVENT_RE = re.compile(r"^\s*EVENT\s+(\S+).*#\s*\$([0-9A-Fa-f]+):")


# --- Loading -------------------------------------------------------------------------------------


def load_vanilla() -> ModuleType:
    """Load ``tables/vanilla.py`` directly, bypassing ``tables/__init__`` (which needs a ROM)."""
    spec = importlib.util.spec_from_file_location("vanilla_direct", VANILLA_PATH)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def object_classes(module: ModuleType) -> list[tuple[str, type]]:
    """Every game-object class defined in vanilla.py, in source order."""
    return [
        (name, obj)
        for name, obj in vars(module).items()
        if isinstance(obj, type) and obj.__module__ == "vanilla_direct"
    ]


def data_fields(cls: type) -> list[tuple[str, object]]:
    """(name, value) for each data field of an object class, in declaration order."""
    return [
        (name, value)
        for name, value in cls.__dict__.items()
        if not name.startswith("__") and name not in META_KEYS
    ]


def camel_to_snake(name: str) -> str:
    snake = re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()
    return snake.removesuffix("_object")


# --- Enum generation -----------------------------------------------------------------------------


def build_enum(filename: str, enum_name: str, base: str) -> str:
    """Parse one lookup module into an ImHex enum; member value = its table index (line order)."""
    text = (LOOKUPS_DIR / filename).read_text(encoding="utf-8")
    members: list[str] = []
    for line in text.splitlines():
        match = _MEMBER_RE.match(line)
        if match:
            members.append(match.group(1))
    lines = [f"enum {enum_name} : {base} {{"]
    lines.extend(f"    {member} = {index}," for index, member in enumerate(members))
    lines.append("};")
    return "\n".join(lines)


def build_enums() -> str:
    blocks = [
        "// --- Lookup enums (from src/lookups/*.py; value = table index) ---",
        *(build_enum(*spec) for spec in LOOKUP_ENUMS),
    ]
    return "\n\n".join(blocks)


# --- Struct / field generation -------------------------------------------------------------------


def field_entry(cls_name: str, field: str, value: object) -> tuple[str, str | None]:
    """Return (struct-member-line, optional-bitfield-definition) for one field."""
    key = (cls_name, field)

    name = safe(field)

    if isinstance(value, bytes):
        # 8 space-separated names = 8 bits of one byte (LSB first, matching src/enums/flags.py).
        bit_names = value.decode("ascii").split()
        bf_name = f"BF_{cls_name}_{field}"
        body = "\n".join(f"    {safe(bit)} : 1;" for bit in bit_names)
        definition = f"bitfield {bf_name} {{  // verify bit order against src/enums/flags.py\n{body}\n}};"
        return f"    {bf_name} {name};", definition

    assert isinstance(value, int)

    if key in LIST_FIELDS:
        element = LIST_FIELDS[key] or "u8"
        return f"    {element} {name}[{value}];", None

    if field in STRING_FIELDS:
        return f"    char {name}[{value}];", None

    if key in ENUM_FIELDS:
        return f"    {ENUM_FIELDS[key]} {name};", None

    if value in INT_TYPE:
        return f"    {INT_TYPE[value]} {name};", None

    # Non power-of-two width with no override: a raw byte blob.
    return f"    u8 {name}[{value}];", None


def build_struct(cls_name: str, cls: type) -> tuple[str, list[str]]:
    """Return (struct definition, list of bitfield definitions it needs)."""
    members: list[str] = []
    bitfields: list[str] = []
    for field, value in data_fields(cls):
        line, bitfield = field_entry(cls_name, field, value)
        members.append(line)
        if bitfield is not None:
            bitfields.append(bitfield)
    struct = f"struct {cls_name} {{\n" + "\n".join(members) + "\n};"
    return struct, bitfields


# --- Placement generation ------------------------------------------------------------------------


def placement(cls_name: str, cls: type) -> str:
    """The global placement(s) for one object, chosen by how its records are addressed."""
    var = camel_to_snake(cls_name)
    attrs = cls.__dict__

    if "pointers" in attrs:
        pointers = attrs["pointers"]
        lines = [f"// {cls_name}: {len(pointers)} scattered records (one placement each)."]
        lines += [f"{cls_name} {var}_{i} @ 0x{int(ptr):X};" for i, ptr in enumerate(pointers)]
        return "\n".join(lines)

    address = int(attrs["address"])
    count = int(attrs["count"])

    if "grouped" in attrs:
        # `base` is a table of `count` little-endian 2-byte pointers; record i lives at base + ptr.
        wrapper = (
            f"struct {cls_name}Ptr {{\n"
            f"    u16 ptr;\n"
            f"    {cls_name} record @ (0x{address:X} + ptr);\n"
            f"}};"
        )
        return f"{wrapper}\n{cls_name}Ptr {var}s[{count}] @ 0x{address:X};"

    return f"{cls_name} {var}s[{count}] @ 0x{address:X};"


def primary_address(cls: type) -> int:
    attrs = cls.__dict__
    if "pointers" in attrs:
        return int(min(attrs["pointers"]))
    return int(attrs["address"])


# --- Eventmap section ----------------------------------------------------------------------------


def build_eventmap_section() -> str:
    """Comment block: each map's index, name, table-entry address, and event-list start."""
    lines = [
        "// --- Eventmap bookmarks (from events_dump.txt) ---",
        "// Event scripts are variable-length bytecode and are not laid out as structs. Names come",
        "// from the `MapEvents` enum; the mapEvents[] table above holds the per-map pointers. The",
        "// event-list address is the script region start reported by the dump.",
    ]
    if not EVENTS_DUMP.exists():
        lines.append("// (events_dump.txt not found - regenerate it to populate this section.)")
        return "\n".join(lines)

    current: dict[str, str] | None = None
    records: list[dict[str, str]] = []
    for raw in EVENTS_DUMP.read_text(encoding="utf-8", errors="replace").splitlines():
        map_match = _MAP_RE.match(raw)
        if map_match:
            current = {
                "index": map_match.group(1),
                "table": map_match.group(2),
                "name": map_match.group(3).strip(),
                "event": "",
            }
            records.append(current)
            continue
        if current is not None and not current["event"]:
            event_match = _EVENT_RE.match(raw)
            # Skip the shared NPC-load script (signature ends in `-XX`); take the first
            # map-specific event list.
            if event_match and not event_match.group(1).endswith("-XX"):
                current["event"] = event_match.group(2)

    for record in records:
        name = record["name"][:28].ljust(28)
        event = f"0x{record['event']}" if record["event"] else "-"
        lines.append(
            f"// MAP {record['index']}  {name}  table @ 0x{record['table']}  event-list @ {event}"
        )
    return "\n".join(lines)


# --- Party block (hand-authored composite view, not derivable from a single table class) ---------

PARTY_BLOCK = """\
// --- Initial party members (composite view; see CharLevel/CharExp/InitialEquip pointers) ---
struct character {
    u16 health;
    u16 mana;
    u16 strength;
    u16 agil;
    u16 intel;
    u16 gut;
    u16 mgr;
};

struct initEquip {
    u16 weapon;
    u16 armor;
    u16 shield;
    u16 helmet;
    u16 ring;
    u16 jewel;
};

struct charLevel {
    u8 level;
};

struct charXp {
    u24 xp;
};

struct FullCharacter {
    u48 name;
    charLevel;
    u24 empty;
    u8 ff;
    charXp;
    initEquip;
};

FullCharacter Maxim @ 0x2B2B0;
FullCharacter Selan @ 0x2B2CD;
FullCharacter Guy @ 0x2B2F1;
FullCharacter Arty @ 0x2B30E;
FullCharacter Tia @ 0x2B333;
FullCharacter Dekar @ 0x2B353;
FullCharacter Lexis @ 0x2B370;"""


# --- Orchestration -------------------------------------------------------------------------------


def generate() -> str:
    module = load_vanilla()
    classes = sorted(object_classes(module), key=lambda item: primary_address(item[1]))

    struct_defs: list[str] = []
    bitfield_defs: list[str] = []
    placements: list[str] = []
    seen_bitfields: set[str] = set()

    for cls_name, cls in classes:
        struct, bitfields = build_struct(cls_name, cls)
        for bitfield in bitfields:
            if bitfield not in seen_bitfields:
                seen_bitfields.add(bitfield)
                bitfield_defs.append(bitfield)
        struct_defs.append(struct)
        placements.append(placement(cls_name, cls))

    sections = [
        HEADER,
        build_enums(),
        "// --- Bitfield definitions (byte flag fields from vanilla.py) ---\n"
        + "\n\n".join(bitfield_defs),
        "// --- Struct definitions (one per object in src/tables/vanilla.py) ---\n"
        + "\n\n".join(struct_defs),
        "// --- Placements (sorted by ROM address) ---\n" + "\n\n".join(placements),
        PARTY_BLOCK,
        build_eventmap_section(),
    ]
    return "\n\n\n".join(sections) + "\n"


def main() -> None:
    OUTPUT.write_text(generate(), encoding="utf-8")
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
