"""Generate helper `Enum`s that give named access to vanilla game structures.

Mirrors the hand-written `Players` enum in ``src/characters.py``::

    class Players(Enum):
        MAXIM = PlayableCharacter.from_index(0)

but produces one enum per enumerable structure, with member names dumped from a
*vanilla* ROM. Run it from the ``src`` directory so package imports resolve, and
force the vanilla table set (the default suggested patch is Frue)::

    cd src
    python tools/generate_lookups.py --file <path-to-vanilla-rom> --vanilla

``--file`` / ``--vanilla`` are consumed by ``args`` (see ``src/args.py``); this
script adds no CLI options of its own so it never clashes with that parser.

Output is written to ``src/lookups/`` (one module per enum, plus ``__init__``).
The generated files are committed; regenerate them with this script rather than
hand-editing.

Excluded, on purpose: ``Boss``/``BossLocation`` (``structures/boss.py`` is a dead
file with no table) and ``Priest`` (a bare stub with no data). ``PlayableCharacter``
is generated here as ``Players`` (mirroring the hand-written ``characters.py``).
"""

import keyword
from collections.abc import Iterator
from pathlib import Path
from typing import Any

# Importing anything from the project pulls in ``args`` (which requires --file)
# and ``helpers.files`` (which opens the ROM). That is intentional: the enum
# member *values* are live instances read from that ROM.
# Only structures whose *member name* is derived from an instance attribute are
# imported here. Index-named structures (Event, Shop, BattleFormation) are still
# generated, but their producers emit a literal expression string instead of
# reading an attribute, so the generator never references the class itself — the
# generated modules import it via each spec's ``imports`` list.
from structures.capsule import CapsuleMonster
from structures.character import PlayableCharacter
from structures.chest import AddressChest, PointerChest
from structures.events import MapEvent
from structures.ip_attack import IPAttack
from structures.item import Item
from structures.maiden import Clare, Lisa, Marie
from structures.monster import Monster, MonsterSprite
from structures.spell import Spell
from structures.word import Word
from structures.zone import Zone
from tables import (
    AncientChest1Object,
    AncientChest2Object,
    BlueChestObject,
    BossFormationObject,
    CapsuleObject,
    CharacterObject,
    ChestObject,
    EventInstObject,
    FormationObject,
    IPAttackObject,
    ItemObject,
    MapEventObject,
    MapFormationsObject,
    MonsterObject,
    ShopObject,
    SpellObject,
    WordObject,
)
from tables.zones import ZoneObject


LOOKUPS_DIR = Path(__file__).resolve().parent.parent / "lookups"

HEADER = (
    "# AUTO-GENERATED by tools/generate_lookups.py - do not edit by hand.\n"
    "# Regenerate with: python tools/generate_lookups.py --file <rom> --vanilla\n"
)


def _clean_text(raw: str | bytes) -> str:
    """Decode/normalise a raw in-game name into printable ASCII characters."""
    if isinstance(raw, bytes):
        # Drop the compression control byte (see Zone.clean_name) and decode.
        raw = raw.replace(b"\x0a", b"").replace(b"\x00", b"").decode("ascii", "ignore")
    # Names are null-padded fixed-width fields; keep only the first segment.
    raw = raw.split("\0")[0]
    return raw


def sanitize(raw: str | bytes, index: int, seen: set[str], *, tag: str) -> str:
    """Turn an in-game name into a unique, valid, upper-snake Python identifier.

    ``tag`` is a short structure prefix used when the name is empty or otherwise
    not a valid identifier start (e.g. ``ITEM`` -> ``ITEM_12``). Collisions are
    disambiguated with the entry's index so every member stays unique.
    """
    text = _clean_text(raw)

    chars = [c if c.isalnum() else "_" for c in text]
    name = "".join(chars).strip("_").upper()
    # Collapse runs of underscores introduced by punctuation/spaces.
    while "__" in name:
        name = name.replace("__", "_")

    if not name:
        # No in-game name: deterministic tag + index (e.g. SHOP_0).
        name = f"{tag}_{index}"
    elif name[0].isdigit() or keyword.iskeyword(name.lower()):
        name = f"{tag}_{name}"

    if name in seen:
        name = f"{name}_{index}"
    seen.add(name)
    return name


def _render(name: str, expr: str) -> str:
    return f"    {name} = {expr}\n"


def write_enum(filename: str, enum_name: str, imports: list[str], doc: str, members: list[str]) -> None:
    body = [
        HEADER,
        "\n",
        *(f"{line}\n" for line in imports),
        "\n\n",
        f"class {enum_name}:\n",
        f'    """{doc}"""\n',
    ]
    body.extend(members)
    if not members:
        body.append("    pass\n")
    path = LOOKUPS_DIR / filename
    path.write_text("".join(body), encoding="utf-8")
    print(f"  wrote {path.relative_to(LOOKUPS_DIR.parent)} ({len(members)} members)")


# --- Per-structure entry producers -------------------------------------------
# Each yields (raw_name, rhs_expr). ``raw_name`` may be None when the structure
# has no in-game name (members are then named by their tag + index).


def items() -> Iterator[tuple[str | bytes | None, str]]:
    for i in range(ItemObject.count):
        yield Item.from_index(i).name_pointer.name, f"Item.from_index({i})"


def monsters() -> Iterator[tuple[str | bytes | None, str]]:
    for i in range(MonsterObject.count):
        yield Monster.from_index(i).name, f"Monster.from_index({i})"


def monster_sprites() -> Iterator[tuple[str | bytes | None, str]]:
    for i in range(MonsterObject.count):
        yield MonsterSprite.from_index(i).name, f"MonsterSprite.from_index({i})"


def spells() -> Iterator[tuple[str | bytes | None, str]]:
    for i in range(len(SpellObject.pointers)):
        yield Spell.from_index(i).name, f"Spell.from_index({i})"


def capsules() -> Iterator[tuple[str | bytes | None, str]]:
    for i in range(CapsuleObject.count):
        yield CapsuleMonster.from_index(i).name, f"CapsuleMonster.from_index({i})"


def zones() -> Iterator[tuple[str | bytes | None, str]]:
    for i in range(ZoneObject.count):
        yield Zone.from_index(i).clean_name, f"Zone.from_index({i})"


def shops() -> Iterator[tuple[str | bytes | None, str]]:
    for i in range(ShopObject.count):
        yield None, f"Shop.from_index({i})"


def formations() -> Iterator[tuple[str | bytes | None, str]]:
    for i in range(FormationObject.count):
        yield None, f"BattleFormation.from_table(FormationObject.address, {i})"


def _chests(obj: Any, obj_name: str) -> Iterator[tuple[str | bytes | None, str]]:
    for i in range(obj.count):
        chest = AddressChest.from_table(obj.address, i)
        yield chest.item.name_pointer.name, f"AddressChest.from_table({obj_name}.address, {i})"


def blue_chests() -> Iterator[tuple[str | bytes | None, str]]:
    yield from _chests(BlueChestObject, "BlueChestObject")


def ancient_chests1() -> Iterator[tuple[str | bytes | None, str]]:
    yield from _chests(AncientChest1Object, "AncientChest1Object")


def ancient_chests2() -> Iterator[tuple[str | bytes | None, str]]:
    yield from _chests(AncientChest2Object, "AncientChest2Object")


def pointer_chests() -> Iterator[tuple[str | bytes | None, str]]:
    for i in range(len(ChestObject.pointers)):
        chest = PointerChest.from_pointer(ChestObject.pointers[i])
        yield chest.item.name_pointer.name, f"PointerChest.from_pointer(ChestObject.pointers[{i}])"


def players() -> Iterator[tuple[str | bytes | None, str]]:
    for i in range(CharacterObject.count):
        yield PlayableCharacter.from_index(i).name, f"PlayableCharacter.from_index({i})"


def words() -> Iterator[tuple[str | bytes | None, str]]:
    for i in range(WordObject.count):
        yield Word.from_index(i).word, f"Word.from_index({i})"


def events() -> Iterator[tuple[str | bytes | None, str]]:
    for i in range(EventInstObject.count):
        yield None, f"Event.from_index({i})"


def map_events() -> Iterator[tuple[str | bytes | None, str]]:
    for i in range(MapEventObject.count):
        yield MapEvent.from_index(i).clean_map_name, f"MapEvent.from_index({i})"


def ip_attacks() -> Iterator[tuple[str | bytes | None, str]]:
    for i in range(len(IPAttackObject.pointers)):
        yield IPAttack.from_pointer(IPAttackObject.pointers[i]).name, f"IPAttack.from_pointer(IPAttackObject.pointers[{i}])"


def boss_formations() -> Iterator[tuple[str | bytes | None, str]]:
    for i in range(BossFormationObject.count):
        yield None, f"BattleFormation.from_pointer(find_table_pointer(BossFormationObject.address, {i}))"


def map_formations() -> Iterator[tuple[str | bytes | None, str]]:
    for i in range(MapFormationsObject.count):
        yield None, f"BattleFormation.from_pointer(find_table_pointer(MapFormationsObject.address, {i}))"


# Structures that are not table-driven get literal, hand-mapped entries.
MAIDENS = [
    (Lisa.maiden_name, "Lisa"),
    (Marie.maiden_name, "Marie"),
    (Clare.maiden_name, "Clare"),
]


# --- Spec table --------------------------------------------------------------

SPECS = [
    ("items.py", "Items", ["from structures.item import Item"],
     "Named access to vanilla items.", "ITEM", items),
    ("monsters.py", "Monsters", ["from structures.monster import Monster"],
     "Named access to vanilla monsters.", "MONSTER", monsters),
    ("monster_sprites.py", "MonsterSprites", ["from structures.monster import MonsterSprite"],
     "Named access to vanilla monster sprites.", "SPRITE", monster_sprites),
    ("spells.py", "Spells", ["from structures.spell import Spell"],
     "Named access to vanilla spells.", "SPELL", spells),
    ("capsules.py", "Capsules", ["from structures.capsule import CapsuleMonster"],
     "Named access to vanilla capsule monsters.", "CAPSULE", capsules),
    ("zones.py", "Zones", ["from structures.zone import Zone"],
     "Named access to vanilla zones.", "ZONE", zones),
    ("shops.py", "Shops", ["from structures.shop import Shop"],
     "Named access to vanilla shops (index-named; shops have no in-game name).", "SHOP", shops),
    ("formations.py", "Formations",
     ["from structures.formation import BattleFormation", "from tables import FormationObject"],
     "Named access to vanilla battle formations (index-named).", "FORMATION", formations),
    ("blue_chests.py", "BlueChests",
     ["from structures.chest import AddressChest", "from tables import BlueChestObject"],
     "Named access to vanilla blue chests (named by contained item).", "CHEST", blue_chests),
    ("ancient_chests1.py", "AncientChests1",
     ["from structures.chest import AddressChest", "from tables import AncientChest1Object"],
     "Named access to vanilla ancient-cave chests, table 1 (named by item).", "CHEST", ancient_chests1),
    ("ancient_chests2.py", "AncientChests2",
     ["from structures.chest import AddressChest", "from tables import AncientChest2Object"],
     "Named access to vanilla ancient-cave chests, table 2 (named by item).", "CHEST", ancient_chests2),
    ("chests.py", "Chests",
     ["from structures.chest import PointerChest", "from tables import ChestObject"],
     "Named access to vanilla map treasure chests (named by contained item).", "CHEST", pointer_chests),
    ("players.py", "Players", ["from structures.character import PlayableCharacter"],
     "Named access to the playable characters.", "PLAYER", players),
    ("words.py", "Words", ["from structures.word import Word"],
     "Named access to vanilla dictionary words.", "WORD", words),
    ("events.py", "Events", ["from structures.events import Event"],
     "Named access to vanilla event instances (index-named).", "EVENT", events),
    ("map_events.py", "MapEvents", ["from structures.events import MapEvent"],
     "Named access to vanilla map event containers (named by map).", "MAP", map_events),
    ("ip_attacks.py", "IPAttacks",
     ["from structures.ip_attack import IPAttack", "from tables import IPAttackObject"],
     "Named access to vanilla IP attacks.", "IP", ip_attacks),
    ("boss_formations.py", "BossFormations",
     ["from structures.formation import BattleFormation", "from tables import BossFormationObject",
      "from helpers.bits import find_table_pointer"],
     "Named access to vanilla boss battle formations (index-named).", "BOSS_FORMATION", boss_formations),
    ("map_formations.py", "MapFormations",
     ["from structures.formation import BattleFormation", "from tables import MapFormationsObject",
      "from helpers.bits import find_table_pointer"],
     "Named access to vanilla map battle formations (index-named).", "MAP_FORMATION", map_formations),
]


def build_members(tag: str, entries: Iterator[tuple[str | bytes | None, str]]) -> list[str]:
    seen: set[str] = set()
    members: list[str] = []
    for index, (raw, expr) in enumerate(entries):
        raw_name = raw if raw is not None else ""
        name = sanitize(raw_name, index, seen, tag=tag)
        members.append(_render(name, expr))
    return members


def generate() -> list[tuple[str, str]]:
    """Generate every enum module; returns (module_stem, enum_name) pairs."""
    LOOKUPS_DIR.mkdir(exist_ok=True)
    exported: list[tuple[str, str]] = []

    for filename, enum_name, imports, doc, tag, producer in SPECS:
        members = build_members(tag, producer())
        write_enum(filename, enum_name, imports, doc, members)
        exported.append((filename[:-3], enum_name))

    # Maidens: not table-driven, mapped by hand.
    seen: set[str] = set()
    maiden_members = [
        _render(sanitize(name, i, seen, tag="MAIDEN"), expr)
        for i, (name, expr) in enumerate(MAIDENS)
    ]
    write_enum(
        "maidens.py", "Maidens",
        ["from structures.maiden import Clare, Lisa, Marie"],
        "Named access to the maidens.", maiden_members,
    )
    exported.append(("maidens", "Maidens"))

    write_init(exported)
    return exported


def write_init(exported: list[tuple[str, str]]) -> None:
    lines = [
        HEADER,
        '"""Named-access helper enums for vanilla game structures (auto-generated)."""\n',
        "\n",
    ]
    for stem, enum_name in exported:
        lines.append(f"from .{stem} import {enum_name}\n")
    names = [enum_name for _, enum_name in exported]
    lines.append("\n\n__all__ = [\n")
    lines.extend(f'    "{n}",\n' for n in sorted(names))
    lines.append("]\n")
    (LOOKUPS_DIR / "__init__.py").write_text("".join(lines), encoding="utf-8")
    print(f"  wrote {Path('lookups') / '__init__.py'} ({len(names)} enums)")


if __name__ == "__main__":
    print(f"Generating lookup enums into {LOOKUPS_DIR} ...")
    generate()
    print("Done.")
